version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: ecofinds-mongodb
    ports:
      - '27017:27017'
    volumes:
      - ecofinds-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecofinds-backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://root:example@mongodb:27017/ecofinds?authSource=admin
      - JWT_SECRET=ecofinds_super_secret_jwt_key_2024
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecofinds-frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

volumes:
  ecofinds-data:
